services:
  postgres:
    image: postgres:15-alpine
    container_name: ims_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: gyaneshshukla/inventory-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ims_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:12345678@postgres:5432/inventory_db
      SECRET_KEY: supersecretkeychangeinproduction
      ENVIRONMENT: production
      PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    image: gyaneshshukla/inventory-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ims_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: